import type { Metadata } from "next";
import { Inter, Newsreader } from "next/font/google";
import { headers } from "next/headers";
import { Analytics } from "@vercel/analytics/react";
import Script from "next/script";
import { SITE } from "@/lib/constants";
import { organizationJsonLd, websiteJsonLd } from "@/lib/jsonld";
import "./globals.css";
import BackToTop from "@/components/BackToTop";

const inter = Inter({ subsets: ["latin"] });

/** Editorial display serif — used for blog/article headlines (and the About editorial layout). */
const newsreader = Newsreader({
  subsets: ["latin"],
  style: ["normal", "italic"],
  variable: "--font-newsreader",
});

export const metadata: Metadata = {
  title: `${SITE.name} | ${SITE.tagline}`,
  description: SITE.description,
  metadataBase: new URL(SITE.url),
  applicationName: SITE.name,
  authors: [{ name: "Marston Ward", url: `${SITE.url}/about` }],
  creator: "Marston Ward",
  publisher: SITE.legalName,
  category: "technology",
  // Site lock: every page carries noindex only while PREVIEW_PASSWORD gates
  // the site. Launch (unsetting the var) flips this and robots.ts together.
  ...(process.env.PREVIEW_PASSWORD
    ? { robots: { index: false, follow: false } }
    : {}),
  manifest: "/manifest.json",
  icons: {
    icon: [
      { url: "/logo/av-mark-favicon.svg", type: "image/svg+xml" },
      { url: "/logo/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/logo/av-favicon-64.png", sizes: "64x64", type: "image/png" },
    ],
    apple: "/logo/av-favicon-192.png",
  },
  openGraph: {
    title: `${SITE.name} | ${SITE.tagline}`,
    description: SITE.ogDescription,
    url: SITE.url,
    siteName: SITE.name,
    locale: "en_US",
    type: "website",
    // OG image is generated by the file-based opengraph-image.tsx routes
    // (root + per-section), which supersede a static /og-image.png.
  },
  twitter: {
    card: "summary_large_image",
    title: `${SITE.name} | ${SITE.tagline}`,
    description: SITE.ogDescription,
    // Twitter image falls back to the generated opengraph-image route.
  },
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nonce = (await headers()).get("x-nonce") ?? undefined;
  void nonce; // available for explicit <Script nonce={nonce}> usage if needed
  return (
    <html lang="en" className="dark scroll-smooth">
      <head>
        {/* Keep feed discovery present even when a page replaces metadata.alternates. */}
        <link
          rel="alternate"
          type="application/rss+xml"
          title={`${SITE.name} Insights`}
          href={`${SITE.url}/feed.xml`}
        />
      </head>
      <body
        className={`${inter.className} ${newsreader.variable} min-h-[100dvh] bg-black text-gray-100 antialiased selection:bg-gray-800 selection:text-white`}
      >
        {/* Skip to main content — accessibility */}
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-[100] focus:rounded-md focus:bg-white focus:px-4 focus:py-2 focus:text-sm focus:font-medium focus:text-black"
        >
          Skip to main content
        </a>
        {children}
        <BackToTop />
        <Analytics />

        {/* Google Analytics */}
        {process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID && (
          <>
            <Script
              src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID}`}
              strategy="afterInteractive"
            />
            <Script id="google-analytics" strategy="afterInteractive">
              {`
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());
                gtag('config', '${process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID}', {
                  page_title: document.title,
                  page_location: window.location.href
                });
              `}
            </Script>
          </>
        )}

        {/* Organization + WebSite JSON-LD */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify([organizationJsonLd, websiteJsonLd]),
          }}
        />
      </body>
    </html>
  );
}
